sam2_config_file: 'configs/sam2.1/sam2.1_hiera_1.yaml'
sam2_checkpoint_file: 'checkpoints/sam2.1/sam2.1_hiera_large.pt'
clip-vit-base-patch32-processor: 'checkpoints/clip-vit-base-patch32/processor'
clip-vit-base-patch32-model: 'checkpoints/clip-vit-base-patch32/model'
memory_vectorstore: 'E:/xingchen/memory_data/chroma_db'
memory_image_dir: 'E:/xingchen/memory_data/images'
